language: rust
rust: 1.30.0

matrix:
  include:
  - os: linux
  - os: osx
    osx_image: xcode10.0 # OS X 10.13 High Sierra
  - os: osx
    osx_image: xcode9.0 # OS X 10.12 Sierra
  - os: osx
    osx_image: xcode8.0 # OS X 10.11 El Capitan
  - os: osx
    osx_image: xcode6.4 # OS X 10.10 Yosemite
  - os: windows

script: cargo test
